apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aksdemo
  template:
    metadata:
      labels:
        app: aksdemo
    spec:
      containers:
      - name: aksdemo
        image: satacr.azurecr.io/sat/azcontainerconnector:latest
      imagePullSecrets:
        - name: myacrsecret
      ports:
      - containerPort: 3000
      env:
      - name: PORT
        value: "3000"
