apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: aksdemo  
spec:  
  replicas: 2  
  selector:  
    matchLabels:  
      app: aksdemo  
  template:  
    metadata:  
      labels:  
        app: aksdemo  
    spec:  
      containers:  
      - name: aksdemo  
        image: satacr.azurecr.io/aksdemo:v1  
        ports:  
        - containerPort: 80  
